# Generated by Django 5.0.2 on 2024-02-14 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second_one', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.IntegerField(),
        ),
    ]
