# Generated by Django 5.0.2 on 2024-02-14 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second_one', '0002_alter_products_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='image',
            field=models.ImageField(default='images/default.jpg', upload_to='images'),
            preserve_default=False,
        ),
    ]
