# Generated by Django 5.0.2 on 2024-02-15 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second_one', '0004_remove_products_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='image',
            field=models.ImageField(default='', upload_to='images'),
        ),
    ]
