# Generated by Django 5.0.2 on 2024-02-15 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second_one', '0005_products_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
