# Generated by Django 5.0.2 on 2024-02-16 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second_one', '0007_alter_products_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='color',
            field=models.CharField(default='default_color_value', max_length=50),
        ),
    ]
